### ISSUE TITLE
Replace for loop with Array.prototype.map

### ISSUE THREAD

**Issue by nishant-jain-94** [sro-boeing-wave-2/english-to-braille-js-assignment-problem-ShashidharB1996#1]
https://github.com/sro-boeing-wave-2/english-to-braille-js-assignment-problem-ShashidharB1996/blob/6b79612a09d5e681bfed7cfd4f1dde9754cbf078/index.js#L14-L16

**Comment by nishant-jain-94** [comment]
Array.prototype.map can be referred from here at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map

**Comment by ShashidharB1996** [comment]
Closed the issue
